export const GET__COURSES="GET__COURSES"
export const UPDATE__COURSE__LIST="UPDATE__COURSE__LIST"
export const DELETE__COURSE='DELETE__COURSE'
export const FETCH_ONE_COURSE = "FETCH_ONE_COURSE"
export const POST_ENROLL_COURSE ="POST_ENROLL_COURSE"